default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: 'tfno2d'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # FNO related
  fno1d:
    in_channels: 2
    out_channels: 1
    modes: 90
    hidden_channels: 128
    lifting_channels: 256
    projection_channels: 256
    n_layers: 4
    domain_padding: None
    domain_padding_mode: 'one-sided'
    fft_norm: 'forward'
    norm: 'group_norm'
    skip: 'linear'
    implementation: 'factorized'
    separable: 0
    preactivation: 0
    half_prec_fourier: False
    half_prec_inverse: False
    stabilizer: None

    use_mlp: 1
    mlp:
        expansion: 0.5
        dropout: 0

    factorization: None
    rank: 0.05
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False

  # Optimizer
  opt:
    n_epochs: 500
    learning_rate: 1e-3
    training_loss: 'h1'
    weight_decay: 2e-6
    amp_autocast: False
    lr: 3e-4
    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 150
    gamma: 0.5
    per_layer_opt: False
    tensorgrad: True
    tensorgrad_scale: 1.00
    rank: 0.25
    act_checkpoint: False
    naive_galore: False
    adamw_support_complex: True
    first_dim_rollup: 2
    update_proj_gap: 25
    galore_proj_type: std

  # Dataset related
  data:
    folder: '/home/ubuntu/data/burgers/burgers.npz' 
    batch_size: 16
    n_train: 800
    test_batch_sizes: [16]
    n_tests: [400]
    spatial_length: 128
    temporal_length: 101

    positional_encoding: True
    encode_input: False
    encode_output: False
    include_endpoint: [True, False]

  profile: False

  # Patching
  patching:
    levels: 0
    padding: 0
    stitching: False

  # Weights and biases
  wandb:
    log: True
    name: "burgers" # If None, config will be used but you can override it here
    group: '' 
    project: "burgers"
    entity: "research-pino_ifno" # put your username here
    sweep: False
    log_output: True
    log_test_interval: 1