cfd: &DEFAULT

  # General
  verbose: True
  arch: 'fnogno'

  # Distributed computing (minimal required)
  distributed:
    use_distributed: False
    seed: 666

  # FNOGNO model parameters (minimal required)
  fnogno:
    data_channels: 1
    out_channels: 1
    fno_n_modes: [32,32,32]  # Match the data resolution

  # Dataset related - using the correct data structure
  data:
    root: 'data/car_cfd/processed-car-pressure-data/data'  # Contains train.txt, test.txt, and data/ subdirectory
    sdf_query_resolution: 32  # Official default
    n_train: 500  # Official default
    n_test: 111   # Official default
    download: False  # Data is already in correct format

  # Optimizer - using official defaults (fixed learning_rate type)
  opt:
    n_epochs: 301  # Official default
    learning_rate: 0.01  # Fixed from bool to float
    training_loss: 'l2'
    testing_loss: 'l2'
    weight_decay: 0
    scheduler: 'StepLR'
    step_size: 50
    gamma: 0.5

  # Weights and biases
  wandb:
    log: True
    name: ""
    group: "car-cfd-fnogno"
    project: "neuralop"
    entity: "sloeschcke"
    sweep: False
    log_output: True
    eval_interval: 1 